export const GET_CURRENT_ORDER_REQUEST: "GET_CURRENT_ORDER_REQUEST" = "GET_CURRENT_ORDER_REQUEST";
export const GET_CURRENT_ORDER_SUCCESS: "GET_CURRENT_ORDER_SUCCESS" = "GET_CURRENT_ORDER_SUCCESS";
export const GET_CURRENT_ORDER_FAILED: "GET_CURRENT_ORDER_FAILED" = "GET_CURRENT_ORDER_FAILED";
